"""Backend-neutral store protocol for Content Research records."""

from __future__ import annotations

from typing import Protocol, TypeVar

from app.content_research.contracts import DirectionContract, RunPolicySnapshot, SamplePolicy
from app.content_research.evidence.models import (
    EvidenceLineageRecord,
    EvidenceRecord,
)
from app.content_research.models import (
    HumanDecisionRecord,
    ObservationEventRecord,
    ResearchBriefRecord,
    ResearchDirectionRecord,
    ResearchPlanRecord,
    ResearchResultSnapshotRecord,
    SubagentTaskRecord,
    TraceRecord,
)
from app.content_research.persistence_models import (
    AggregateClaimRecord,
    BudgetLedgerEntryRecord,
    CanonicalSourceRecord,
    ClaimAdmissionDecisionRecord,
    ClaimCandidateRecord,
    CrossDirectionRecord,
    DirectionalEvidencePacketRecord,
    DirectionResultDecisionRecord,
    DirectionSourceProjectionRecord,
    MarketingConclusionCandidateRecord,
    MarketingConclusionDecisionRecord,
    ReportDraftRecord,
    ReportFaithfulnessDecisionRecord,
    ReportPublicationRecord,
    StageCheckpointRecord,
    WeakSignalRecord,
)
from app.content_research.scope_contract import CoverageSnapshot, ResearchScopeContract, ScopeAuditEvent

TypedRecordT = TypeVar("TypedRecordT", bound=CanonicalSourceRecord | DirectionSourceProjectionRecord | DirectionalEvidencePacketRecord | ClaimCandidateRecord | ClaimAdmissionDecisionRecord | DirectionResultDecisionRecord | WeakSignalRecord | CrossDirectionRecord | AggregateClaimRecord | MarketingConclusionCandidateRecord | MarketingConclusionDecisionRecord | StageCheckpointRecord | BudgetLedgerEntryRecord | ReportDraftRecord | ReportFaithfulnessDecisionRecord | ReportPublicationRecord)


class ContentResearchStore(Protocol):
    def save_scope_contract(self, contract: ResearchScopeContract) -> ResearchScopeContract: ...
    def get_scope_contract(self, workflow_run_id: str, *, version: int) -> ResearchScopeContract | None: ...
    def list_scope_contracts(self, workflow_run_id: str) -> list[ResearchScopeContract]: ...
    def save_coverage_snapshot(self, snapshot: CoverageSnapshot) -> CoverageSnapshot: ...
    def get_coverage_snapshot(self, workflow_run_id: str, *, version: int) -> CoverageSnapshot | None: ...
    def append_scope_audit_event(self, event: ScopeAuditEvent) -> ScopeAuditEvent: ...
    def list_scope_audit_events(self, workflow_run_id: str, *, version: int) -> list[ScopeAuditEvent]: ...
    def save_run_policy_snapshot(self, snapshot: RunPolicySnapshot) -> RunPolicySnapshot: ...
    def get_run_policy_snapshot(self, snapshot_id: str) -> RunPolicySnapshot | None: ...
    def get_run_policy_snapshot_for_workflow(self, workflow_run_id: str) -> RunPolicySnapshot | None: ...
    def save_sample_policy(self, policy: SamplePolicy) -> SamplePolicy: ...
    def get_sample_policy(self, sample_policy_id: str) -> SamplePolicy | None: ...
    def save_direction_contract(self, contract: DirectionContract) -> DirectionContract: ...
    def list_direction_contracts(self, snapshot_id: str) -> list[DirectionContract]: ...
    def save_canonical_source(self, source: CanonicalSourceRecord) -> CanonicalSourceRecord: ...
    def resolve_canonical_source(self, source: CanonicalSourceRecord) -> CanonicalSourceRecord: ...
    def get_canonical_source(self, source_id: str) -> CanonicalSourceRecord | None: ...
    def get_typed_record(self, record_type: type[TypedRecordT], record_id: str) -> TypedRecordT | None: ...
    def list_typed_records(self, record_type: type[TypedRecordT]) -> list[TypedRecordT]: ...
    def save_direction_source_projection(self, record: DirectionSourceProjectionRecord) -> DirectionSourceProjectionRecord: ...
    def save_directional_evidence_packet(self, record: DirectionalEvidencePacketRecord) -> DirectionalEvidencePacketRecord: ...
    def list_direction_source_projections(self, workflow_run_id: str, research_direction_id: str, *, offset: int = 0, limit: int = 50) -> list[DirectionSourceProjectionRecord]: ...
    def count_run_independent_sources(self, workflow_run_id: str) -> int: ...
    def list_directional_evidence_packets(self, workflow_run_id: str, research_direction_id: str, *, offset: int = 0, limit: int = 50) -> list[DirectionalEvidencePacketRecord]: ...
    def save_claim_candidate(self, record: ClaimCandidateRecord) -> ClaimCandidateRecord: ...
    def list_claim_candidates(self, workflow_run_id: str, research_direction_id: str) -> list[ClaimCandidateRecord]: ...
    def save_claim_admission_decision(self, record: ClaimAdmissionDecisionRecord) -> ClaimAdmissionDecisionRecord: ...
    def save_direction_result_decision(self, record: DirectionResultDecisionRecord) -> DirectionResultDecisionRecord: ...
    def save_weak_signal(self, record: WeakSignalRecord) -> WeakSignalRecord: ...
    def save_cross_direction_record(self, record: CrossDirectionRecord) -> CrossDirectionRecord: ...
    def save_aggregate_claim(self, record: AggregateClaimRecord) -> AggregateClaimRecord: ...
    def save_marketing_conclusion_candidate(self, record: MarketingConclusionCandidateRecord) -> MarketingConclusionCandidateRecord: ...
    def list_marketing_conclusion_candidates(self, workflow_run_id: str, research_plan_id: str) -> list[MarketingConclusionCandidateRecord]: ...
    def save_marketing_conclusion_decision(self, record: MarketingConclusionDecisionRecord) -> MarketingConclusionDecisionRecord: ...
    def list_marketing_conclusion_decisions(self, workflow_run_id: str, research_plan_id: str) -> list[MarketingConclusionDecisionRecord]: ...
    def save_stage_checkpoint(self, record: StageCheckpointRecord) -> StageCheckpointRecord: ...
    def save_budget_ledger_entry(self, record: BudgetLedgerEntryRecord) -> BudgetLedgerEntryRecord: ...
    def save_report_draft(self, record: ReportDraftRecord) -> ReportDraftRecord: ...
    def save_report_faithfulness_decision(self, record: ReportFaithfulnessDecisionRecord) -> ReportFaithfulnessDecisionRecord: ...
    def save_report_publication(self, record: ReportPublicationRecord) -> ReportPublicationRecord: ...
    def save_brief(self, brief: ResearchBriefRecord) -> ResearchBriefRecord: ...

    def get_brief(self, brief_id: str) -> ResearchBriefRecord | None: ...

    def get_brief_by_presearch_attempt(self, attempt_id: str) -> ResearchBriefRecord | None: ...

    def get_brief_by_workflow(self, workflow_run_id: str) -> ResearchBriefRecord | None: ...

    def save_plan(self, plan: ResearchPlanRecord) -> ResearchPlanRecord: ...

    def get_plan(self, plan_id: str) -> ResearchPlanRecord | None: ...

    def list_plans_for_brief(self, brief_id: str) -> list[ResearchPlanRecord]: ...

    def save_direction(self, direction: ResearchDirectionRecord) -> ResearchDirectionRecord: ...

    def list_directions_for_plan(self, plan_id: str) -> list[ResearchDirectionRecord]: ...

    def save_subagent_task(self, task: SubagentTaskRecord) -> SubagentTaskRecord: ...

    def get_subagent_task(self, task_id: str) -> SubagentTaskRecord | None: ...

    def list_subagent_tasks_for_workflow(self, workflow_run_id: str) -> list[SubagentTaskRecord]: ...

    def save_trace(self, trace: TraceRecord) -> TraceRecord: ...

    def get_trace(self, trace_id: str) -> TraceRecord | None: ...

    def list_traces_for_workflow(self, workflow_run_id: str) -> list[TraceRecord]: ...

    def append_observation_event(self, event: ObservationEventRecord) -> ObservationEventRecord: ...

    def list_observation_events(self, trace_id: str) -> list[ObservationEventRecord]: ...

    def save_evidence_record(self, record: EvidenceRecord) -> EvidenceRecord: ...

    def get_evidence_record(self, evidence_id: str) -> EvidenceRecord | None: ...

    def list_evidence_records(
        self,
        *,
        workflow_run_id: str | None = None,
        research_plan_id: str | None = None,
        research_direction_id: str | None = None,
        subagent_task_id: str | None = None,
    ) -> list[EvidenceRecord]: ...

    def append_evidence_lineage(self, lineage: EvidenceLineageRecord) -> EvidenceLineageRecord: ...

    def list_evidence_lineage(self, evidence_record_id: str) -> list[EvidenceLineageRecord]: ...

    def save_result_snapshot(self, snapshot: ResearchResultSnapshotRecord) -> ResearchResultSnapshotRecord: ...

    def get_result_snapshot(self, snapshot_id: str) -> ResearchResultSnapshotRecord | None: ...

    def list_result_snapshots_for_workflow(self, workflow_run_id: str) -> list[ResearchResultSnapshotRecord]: ...

    def append_human_decision(self, decision: HumanDecisionRecord) -> HumanDecisionRecord: ...

    def get_human_decision_by_request(
        self,
        *,
        workflow_run_id: str,
        target_type: str,
        target_id: str,
        decision_request_id: str,
    ) -> HumanDecisionRecord | None: ...

    def list_human_decisions_for_workflow(self, workflow_run_id: str) -> list[HumanDecisionRecord]: ...

    def list_current_human_decisions_for_workflow(self, workflow_run_id: str) -> list[HumanDecisionRecord]: ...
