"""Backend-neutral store protocol for Content Research records."""

from __future__ import annotations

from typing import Protocol

from app.content_research.evidence.models import (
    EvidenceBundleItemRecord,
    EvidenceBundleRecord,
    EvidenceLineageRecord,
    EvidenceRecord,
)
from app.content_research.models import (
    HumanDecisionRecord,
    ObservationEventRecord,
    ResearchBriefRecord,
    ResearchDirectionRecord,
    ResearchPlanRecord,
    ResearchResultSnapshotRecord,
    SubagentTaskRecord,
    TraceRecord,
)


class ContentResearchStore(Protocol):
    def save_brief(self, brief: ResearchBriefRecord) -> ResearchBriefRecord: ...

    def get_brief(self, brief_id: str) -> ResearchBriefRecord | None: ...

    def get_brief_by_presearch_attempt(self, attempt_id: str) -> ResearchBriefRecord | None: ...

    def get_brief_by_workflow(self, workflow_run_id: str) -> ResearchBriefRecord | None: ...

    def save_plan(self, plan: ResearchPlanRecord) -> ResearchPlanRecord: ...

    def get_plan(self, plan_id: str) -> ResearchPlanRecord | None: ...

    def list_plans_for_brief(self, brief_id: str) -> list[ResearchPlanRecord]: ...

    def save_direction(self, direction: ResearchDirectionRecord) -> ResearchDirectionRecord: ...

    def list_directions_for_plan(self, plan_id: str) -> list[ResearchDirectionRecord]: ...

    def save_subagent_task(self, task: SubagentTaskRecord) -> SubagentTaskRecord: ...

    def get_subagent_task(self, task_id: str) -> SubagentTaskRecord | None: ...

    def list_subagent_tasks_for_workflow(self, workflow_run_id: str) -> list[SubagentTaskRecord]: ...

    def save_trace(self, trace: TraceRecord) -> TraceRecord: ...

    def get_trace(self, trace_id: str) -> TraceRecord | None: ...

    def list_traces_for_workflow(self, workflow_run_id: str) -> list[TraceRecord]: ...

    def append_observation_event(self, event: ObservationEventRecord) -> ObservationEventRecord: ...

    def list_observation_events(self, trace_id: str) -> list[ObservationEventRecord]: ...

    def save_evidence_record(self, record: EvidenceRecord) -> EvidenceRecord: ...

    def get_evidence_record(self, evidence_id: str) -> EvidenceRecord | None: ...

    def list_evidence_records(
        self,
        *,
        workflow_run_id: str | None = None,
        research_plan_id: str | None = None,
        research_direction_id: str | None = None,
        subagent_task_id: str | None = None,
    ) -> list[EvidenceRecord]: ...

    def append_evidence_lineage(self, lineage: EvidenceLineageRecord) -> EvidenceLineageRecord: ...

    def list_evidence_lineage(self, evidence_record_id: str) -> list[EvidenceLineageRecord]: ...

    def save_evidence_bundle(self, bundle: EvidenceBundleRecord) -> EvidenceBundleRecord: ...

    def get_evidence_bundle(self, bundle_id: str) -> EvidenceBundleRecord | None: ...

    def list_evidence_bundles_for_workflow(self, workflow_run_id: str) -> list[EvidenceBundleRecord]: ...

    def add_evidence_bundle_item(self, item: EvidenceBundleItemRecord) -> EvidenceBundleItemRecord: ...

    def list_evidence_bundle_items(self, bundle_id: str) -> list[EvidenceBundleItemRecord]: ...

    def save_result_snapshot(self, snapshot: ResearchResultSnapshotRecord) -> ResearchResultSnapshotRecord: ...

    def get_result_snapshot(self, snapshot_id: str) -> ResearchResultSnapshotRecord | None: ...

    def list_result_snapshots_for_workflow(self, workflow_run_id: str) -> list[ResearchResultSnapshotRecord]: ...

    def append_human_decision(self, decision: HumanDecisionRecord) -> HumanDecisionRecord: ...

    def get_human_decision_by_request(
        self,
        *,
        workflow_run_id: str,
        target_type: str,
        target_id: str,
        decision_request_id: str,
    ) -> HumanDecisionRecord | None: ...

    def list_human_decisions_for_workflow(self, workflow_run_id: str) -> list[HumanDecisionRecord]: ...

    def list_current_human_decisions_for_workflow(self, workflow_run_id: str) -> list[HumanDecisionRecord]: ...
